client_config_backend: settings
client_config:
  client_id: 948550438874-fefpdkrers91t3ia2a58t333mft1hoig.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install